[package]
name = "iai-callgrind"
version = "0.1.0"
authors = ["Joining7943 <joining@posteo.de>", "Brook Heisler <redattack34@gmail.com>"]
edition = "2021"
rust-version = "1.45.0"
description = "One-shot benchmarking library based on callgrind"
readme = "README.md"
homepage = "https://github.com/Joining7943/iai-callgrind"
repository = "https://github.com/Joining7943/iai-callgrind"
license = "Apache-2.0 AND MIT"
keywords = ["iai", "benchmark", "callgrind", "valgrind"]
categories = ["development-tools::profiling", "development-tools::testing"]

[dependencies]
cfg-if = "1.0"

[features]
real_blackbox = []
default = []

[[bench]]
name = "test_regular_bench"
harness = false
