[package]
name = "benchmark-tests"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Joining7943 <joining@posteo.de>"]
rust-version = "1.60.0"
description = "Tests for iai-callgrind"
readme = "../README.md"
homepage = "https://github.com/iai-callgrind/iai-callgrind"
repository = "https://github.com/iai-callgrind/iai-callgrind"
license = "Apache-2.0 OR MIT"

[dependencies]
iai-callgrind = { path = "../iai-callgrind" }

[[bin]]
name = "benchmark-tests-printenv"
path = "src/benchmark-tests-printenv.rs"

[[bin]]
name = "benchmark-tests-cat"
path = "src/benchmark-tests-cat.rs"

[[bin]]
name = "benchmark-tests-exit"
path = "src/benchmark-tests-exit.rs"

[[bin]]
name = "benchmark-tests-echo"
path = "src/benchmark-tests-echo.rs"

[[bench]]
name = "test_bin_bench_with_fixtures"
harness = false

[[bench]]
name = "test_bin_bench_with_exit"
harness = false

[[bench]]
name = "test_bin_bench_groups"
harness = false

[[bench]]
name = "test_bin_bench_flamegraph"
harness = false

[[bench]]
name = "test_lib_bench_flamegraph"
harness = false

[[bench]]
name = "test_lib_bench_groups"
harness = false

[[bench]]
name = "test_lib_bench_groups_envs"
harness = false

[[bench]]
name = "test_lib_bench_readme_example_fibonacci"
harness = false
