[package]
name = "benchmark-tests"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Joining7943 <joining@posteo.de>"]
rust-version = "1.60.0"
description = "Tests for iai-callgrind"
readme = "../README.md"
homepage = "https://github.com/Joining7943/iai-callgrind"
repository = "https://github.com/Joining7943/iai-callgrind"
license = "Apache-2.0 AND MIT"

[dependencies]
iai-callgrind = { path = "../iai-callgrind" }

[[bench]]
name = "test_bin_bench"
harness = false
