[package]
name = "iai-callgrind"
version = "0.3.1"
authors = ["Joining7943 <joining@posteo.de>", "Brook Heisler <redattack34@gmail.com>"]
edition = "2021"
rust-version = "1.60.0"
description = "High-precision and consistent benchmarking framework/harness for Rust"
readme = "../README.md"
homepage = "https://github.com/Joining7943/iai-callgrind"
repository = "https://github.com/Joining7943/iai-callgrind"
license = "Apache-2.0 AND MIT"
keywords = ["iai", "benchmark", "callgrind", "valgrind"]
categories = ["development-tools::profiling", "development-tools::testing"]
