[package]
name = "iai-callgrind-macros"
version = "0.1.0"
edition = "2021"
rust-version = "1.66.0"
authors = ["Joining7943 <joining@posteo.de>"]
description = "Proc macros for iai-callgrind, a high-precision and consistent benchmarking framework/harness for Rust"
readme = "README.md"
homepage = "https://github.com/iai-callgrind/iai-callgrind"
repository = "https://github.com/iai-callgrind/iai-callgrind"
license = "Apache-2.0 OR MIT"
keywords = ["iai", "benchmark", "callgrind", "valgrind"]
categories = ["development-tools::profiling", "development-tools::testing"]

[lib]
proc-macro = true

[dependencies]
proc-macro-error = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
