[package]
name = "iai-callgrind-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1"
proc-macro2 = ">=1.0.60, <2"
quote = "1"
syn = { version = ">=2.0.1, <3", features = ["full", "extra-traits"] }

[dev-dependencies]
pretty_assertions = "1"
