[package]
name = "iai-callgrind-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0"

[dev-dependencies]
iai-callgrind = { path = "../iai-callgrind", version = "0.1.0" }

[[bin]]
name = "iai-callgrind-runner"
path = "src/main.rs"
test = true
bench = true

[[bench]]
name = "test_regular_bench"
harness = false

[[bench]]
path = "benches/subdir/test_subdir_bench.rs"
name = "test_subdir_bench"
harness = false
