[package]
name = "iai-callgrind-runner"
version = "0.7.1"
edition = "2021"
rust-version = "1.60.0"
authors = [
  "Joining7943 <joining@posteo.de>",
  "Brook Heisler <redattack34@gmail.com>",
]
description = "Binary package needed by the iai-callgrind library"
readme = "README.md"
homepage = "https://github.com/Joining7943/iai-callgrind"
repository = "https://github.com/Joining7943/iai-callgrind"
license = "Apache-2.0 OR MIT"
keywords = ["iai", "benchmark", "callgrind", "valgrind"]
categories = ["development-tools::profiling", "development-tools::testing"]

[features]
api = ["dep:serde"]
default = ["runner", "api"]
runner = [
  "dep:bincode",
  "dep:cargo_metadata",
  "dep:colored",
  "dep:env_logger",
  "dep:indexmap",
  "dep:inferno",
  "dep:log",
  "dep:sanitize-filename",
  "dep:shlex",
  "dep:tempfile",
  "dep:version-compare",
  "dep:which",
]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[dependencies]
bincode = { version = "1", optional = true }
cargo_metadata = { version = "0.17", optional = true }
colored = { version = ">=1.6, <3", optional = true }
env_logger = { version = ">=0.7, <0.11", optional = true }
indexmap = { version = "1.9", optional = true, features = ["serde"] }
inferno = { version = "0.11.10", optional = true, default-features = false, features = [
  'multithreaded',
] }
log = { version = "0.4", optional = true }
sanitize-filename = { version = "0.5", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
shlex = { version = "1", optional = true }
tempfile = { version = "3", optional = true }
version-compare = { version = "0.1", optional = true }
which = { version = "4", optional = true }

[dev-dependencies]
rstest = ">=0.17, <0.19"

[[bin]]
name = "iai-callgrind-runner"
path = "src/main.rs"
test = true
bench = true
